_BASE_: "./Base-BoundaryFormer-RCNN-FPN.yaml"
MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "/home/ali.tohidifar75/detectron_test_exp1/train/floorplandata_train/COCO-InstanceSegmentation/boundaryformer_rcnn_R_101_FPN_3x.yaml/default/model_final.pth"
  MASK_ON: True  
  ROI_MASK_HEAD:
    NAME: "BoundaryFormerPolygonHead"
    POOLER_TYPE: ""
  BOUNDARY_HEAD:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    # IN_FEATURES: ["p2", "p2", "p3", "p4", "p5", "p5"]
    PRED_WITHIN_BOX: True
    POLY_NUM_PTS: 128
    CLS_AGNOSTIC_MASK: True
    UPSAMPLING_BASE_NUM_PTS: 16
    UPSAMPLING: True
  DIFFRAS:
    RESOLUTIONS: (64, 64, 64, 64, 64, 64, 64, 64)
    USE_RASTERIZED_GT: False
    INV_SMOOTHNESS_SCHED: (0.1,)
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    PROPOSAL_ONLY_GT: False
SOLVER:
  STEPS: (210000, 250000)
  # MAX_ITER: 270000
  MAX_ITER: 540000
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.20 # more regularization needed than R50/1x.
  WEIGHT_DECAY_NORM: 0.0
  IMS_PER_BATCH: 16
  CLIP_GRADIENTS:
    ENABLED: False
  CHECKPOINT_PERIOD: 15000
DATASETS:
  TRAIN: ("floorplandata_train",)
  TEST: ("floorplandata_val",)
  # TRAIN: ("coco_2017_train",)
  # TEST: ("coco_2017_val",)
INPUT:
  # Is this mandatory for 3x? It definitely helps.
  DETR_STYLE_AUG: False
  MAX_SIZE_TRAIN: 2666
  # MIN_SIZE_TRAIN: (1280, 1344, 1408, 1472, 1536, 1600)
  MIN_SIZE_TRAIN: (1120, 1176, 1232, 1288, 1344, 1400)
  MAX_SIZE_TEST: 2666
  MIN_SIZE_TEST: 1600

TEST:
  EVAL_PERIOD: 5000
VIS_PERIOD: 0  
